Change previous url admin login api
AT-PHPIntership/book-library pull request #108
Opened 2018-01-22 07:21 UTC by at-annguyen

## Description
Change previous url admin login api
## Reference Requirements
- Product Backlog ID: PBI-1
- Task ID: TI-1.3

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-01-22 07:48 UTC, at-anhngo commented
LGTM

2018-01-23 01:49 UTC, at-duyho commented on app/Http/Controllers/Admin/LoginController.php
> +        session(['url_previous' => session()->get('_previous')]);
- sao lại dùng array?

2018-01-23 01:50 UTC, ghost requested changes
check my comment

2018-01-23 15:34 UTC, at-duyho commented on app/Http/Controllers/Admin/LoginController.php
> +        $checkURL = session('url_previous');
- Em phải kiểm tra và clear session sau khi họ login thành công. trong trường hợp họ không login thành công thì sẽ không đúng. em check lại.

2018-01-23 15:34 UTC, ghost requested changes
- check my comment

2018-01-24 03:29 UTC, at-annguyen commented on app/Http/Controllers/Admin/LoginController.php
> +        $checkURL = session('url_previous');
- clear session ngay tại đó cũng được mà anh. mình lưu session bằng biến $checkURL rồi thì session này không dùng đến

2018-01-24 07:44 UTC, at-duyho commented on app/Http/Controllers/Admin/LoginController.php
> +                $checkURL = session('url_previous')[0];
- this code has exception when session('url_previous') return null. please check it.

2018-01-24 07:44 UTC, ghost requested changes
check my comment

2018-01-25 02:31 UTC, at-duyho commented on app/Http/Controllers/Admin/LoginController.php
> +        session()->get('_previous')['url'];
- remove it.

2018-01-25 02:33 UTC, at-duyho commented on app/Http/Controllers/Admin/LoginController.php
> +                if (!empty($checkURL) && $checkURL != route('login')) {
you should use:
` if (empty($checkURL) || $checkURL == route('login')) {
       $checkURL="/"
}
return redirect($checkURL);
`

2018-01-25 02:34 UTC, ghost requested changes
check my comment.

2018-01-25 15:51 UTC, ghost approved these changes
LGTM

2018-01-25 15:51 UTC, merged