Admin send letter borrower
AT-PHPIntership/book-library pull request #125
Opened 2018-01-24 10:25 UTC by at-annguyen

## Description
reminder button and remind letter content
## Reference Requirements
- Product Backlog ID: PBI-3
- Task ID: TI-3.1

## Reference Isuees
#{issue_id}

## Migrations
YES

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-01-26 04:45 UTC, ghost requested changes
Check my comment

2018-01-26 04:45 UTC, at-anhngo commented on app/Http/Controllers/Admin/SendMailController.php
> +use Illuminate\Http\Request;
cái này không xài thì xóa đi

2018-01-29 07:30 UTC, ghost requested changes
Check my comment

2018-01-29 07:30 UTC, at-anhngo commented on routes/web.php
> +Route::get('mail', 'Admin\SendMailController@sendMail')->name('sendMail');
route này không có middleware thì ai cũng có thể vào được

2018-01-29 08:16 UTC, ghost approved these changes
LGTM

2018-01-30 01:14 UTC, at-huydq commented
good job, LGTM.

2018-01-30 01:14 UTC, merged