Delete comment
AT-PHPIntership/book-library pull request #136
Opened 2018-01-29 07:32 UTC by at-luanle

## Description
Delete Comment
## Reference Requirements
- Product Backlog ID: #PBI-11: As a manager, in post detail page, I can delete post or comment without reload page
- Task ID: #11.4 Delete comments

## Reference Isuees
#{issue_id}

## Migrations
 NO

## Impacted Areas in Application
List general components of the application that this PR will affect:
 app/Http/Controllers/Admin/PostController.php
app/Model/Comment.php
app/Http/Controllers/Admin/CommentController.php
app/Helpers/common.php
-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

explain (update `comments` set `deleted_at` = '2018-01-29 07:31:33', `updated_at` = '2018-01-29 07:31:33' 
where `comments`.`parent_id` = '2' and `comments`.`parent_id` is not null and `comments`.`deleted_at` is null)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-01-29 09:58 UTC, ghost reviewed
please check my comments.

2018-01-29 09:58 UTC, at-nghiavo commented on app/Helpers/common.php
> +                                $body .= '<img class="img-thumbnail" src="' . asset("images/books/no-image.png") . '" alt="User profile picture">';
trong config->image có tạo sẵn rồi, a có thể sử dụng thay cho dùng đường dẫn.

2018-01-29 09:58 UTC, at-nghiavo commented on app/Helpers/common.php
> +                                $body .= '<img class="img-thumbnail" src="' . asset("images/books/no-image.png") . '" alt="User profile picture">';
translate cho content trong img -> alt luôn a

2018-01-29 09:58 UTC, at-nghiavo commented on resources/views/backend/posts/show.blade.php
> +                  <img class="img-thumbnail" src="{{ asset('images/books/'.$post->image_url) }}" alt="User profile picture">
dùng đường dẫn có sẵn trong config.
translate content trong alt

2018-01-29 09:58 UTC, at-nghiavo commented on app/Http/Controllers/CommentController.php
> +     * Show the form with book data for edit book.
Show the form with book data for delete book chứ anh.

2018-01-29 09:58 UTC, at-nghiavo commented on resources/views/backend/posts/show.blade.php
> +            <div id="message" class="">
class không dùng nên xóa đi anh

2018-01-29 09:59 UTC, at-nghiavo commented
SQL query and explain trong description chưa đúng nha anh Luân.

2018-01-31 02:26 UTC, at-nghiavo commented
conflicts rồi nha anh

2018-01-31 04:04 UTC, ghost requested changes
please check my comments

2018-01-31 04:04 UTC, at-nghiavo commented on resources/views/backend/posts/show.blade.php
> +<<<<<<< HEAD
còn conflicts a

2018-01-31 04:04 UTC, at-nghiavo commented on resources/views/backend/posts/show.blade.php
> +>>>>>>> b41158755f865c09264be2efa80306edcf8943f1
conflicts chưa fix xong

2018-01-31 04:04 UTC, at-nghiavo commented on app/Http/Controllers/Admin/CommentController.php
> +     * Show the form with book data for edit book.
fucntion destroy sao chú thích for edit book vậy a

2018-01-31 04:04 UTC, at-nghiavo commented on app/Http/Controllers/Admin/CommentController.php
> +     * @param int     $id      id
id của gì vậy a

2018-01-31 04:33 UTC, ghost approved these changes

2018-01-31 04:34 UTC, at-nghiavo commented
LGTM

2018-01-31 09:54 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/CommentController.php
> +    public function destroy(Request $request, $id)
destroy thì k cần $request đâu, chỉ cần $id thôi

2018-01-31 09:56 UTC, at-xinhnguyen commented on app/Model/Post.php
> +        return $this->image ? $this->image: asset(config('image.books.default_path').self::DEFAULT_IMAGE_POST);
check lại convention `space` với Luân

2018-01-31 09:58 UTC, at-xinhnguyen commented on public/js/delete_comment.js
> +$(document).ready(function(){
nên viết theo kiểu đối tượng đễ dễ xử lý và clear Luân ơi. bữa trước cho chỉ Minh với Nghĩa rồi. follow theo file category.js và user.js

2018-01-31 10:22 UTC, at-xinhnguyen commented on resources/views/backend/posts/show.blade.php
> +                <button type="button" id="btnOK" class="btn btn-danger" data-dismiss="modal">{{ __('confirm.ok') }}</button>
convention code html  phải dùng dấu `-` giữa các từ

2018-02-01 03:09 UTC, at-xinhnguyen commented on resources/views/backend/posts/show.blade.php
> +                                <li class="active"><a href="#activity" data-toggle="tab">Comments</a></li>
please trans for `comments`

2018-02-01 03:17 UTC, at-xinhnguyen commented on public/js/delete_comment.js
> +var comment = (function() {
nên đặt tên file là comment hoặc post.

2018-02-01 03:27 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/CommentController.php
> +        if ($request->ajax()) {
chỗ này Luân dùng request()->ajax() thay cho $request và remvove biến $request đi

2018-02-01 03:29 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/CommentController.php
> +            return response()->json(204);
chỗ này Luân use Symfony\Component\HttpFoundation\Response
và thay 204 thành Response::HTTP_NO_CONTENT. chứ dùng 204 là hard code rồi

2018-02-01 03:29 UTC, at-xinhnguyen commented on public/js/delete_comment.js
> +                },
delete thì k cần truyền data lên

2018-02-01 04:01 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/CommentController.php
> +class CommentController extends Controller
ajax thì nên để bên thư mục Http/Api

2018-02-01 07:30 UTC, at-xinhnguyen commented on app/Http/Controllers/Api/CommentController.php
> +        Comment::find($id)->delete();
chỗ này sẽ bị lỗi nếu Comment::find($id) không tìm thấy

2018-02-01 08:40 UTC, at-xinhnguyen commented on routes/web.php
> +    Route::delete('comments/{id}/destroy', 'CommentController@destroy');
nên thế này cho hay 
Route::resource('comments', 'CommentController', ['only' => ['delete']]);

2018-02-01 08:41 UTC, ghost approved these changes
LGTM

2018-02-01 08:41 UTC, merged