Admin send letter pop up
AT-PHPIntership/book-library pull request #138
Opened 2018-01-29 09:53 UTC by at-annguyen

## Description
Create pop-up confirm send email
## Reference Requirements
- Product Backlog ID: PBI-3
- Task ID: TI-3.3

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-01-29 10:01 UTC, ghost requested changes
Check my comment

2018-01-29 10:01 UTC, at-anhngo commented on public/app/js/borrow.js
> +})
cần 1 khoảng trống

2018-01-29 10:26 UTC, ghost approved these changes

2018-01-29 10:26 UTC, at-anhngo commented
LGTM

2018-01-30 03:32 UTC, ghost reviewed
please check my comment

2018-01-30 03:32 UTC, at-huydq commented on resources/views/backend/books/borrow.blade.php
> +<!-- Modal -->
tạo file `modal_confirm` rồi bỏ vào thư mục `backend/books/partials` giúp anh

2018-01-30 03:32 UTC, at-huydq commented on resources/views/backend/books/borrow.blade.php
> +<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
remove

2018-01-30 03:32 UTC, at-huydq commented on resources/views/backend/books/borrow.blade.php
> +<script src="{{ asset('app/js/borrow.js') }}"></script>
tạo `yield` `script-custom` bên `Main` nhá

2018-01-30 03:48 UTC, at-huydq commented on routes/web.php
> +    Route::get('mail', 'SendMailController@sendMail')->name('sendMail');
Send Mail là Method Post nhé

2018-01-30 03:48 UTC, at-huydq commented on resources/views/backend/books/borrow.blade.php
> +                                    <form method="GET" action="{{ route('sendMail') }}" id="form-confirm-{{$borrowing->id}}">
`Post` not `Get`

2018-01-30 05:08 UTC, at-huydq commented
https://media0.giphy.com/media/3osxYdek8wYWCOLgT6/200_d.webp?cid=cafe52e95a6ffda55a3656412edf66fc
LGTM

2018-01-30 05:10 UTC, merged