Delete book and its relationship
AT-PHPIntership/book-library pull request #150
Opened 2018-02-01 03:53 UTC by at-minhphan

## Description
Delete book and its relationship when click button delete and reload page. Can restore book when click button restore.
## Reference Requirements
- Product Backlog ID: PBI-8
- Task ID: TI-3

## Reference Isuees
None

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

- app/Http/Controllers/Admin/BookController.php
- public/css/main.css
- resources/views/backend/books/list.blade.php
- resources/views/backend/layouts/partials/js.blade.php
- routes/web.php

## SQL query and `explain`
- update `borrowings` set `deleted_at` = '2018-02-01 03:44:14', `updated_at` = '2018-02-01 03:44:14' where `id` = '3'
- update `qrcodes` set `deleted_at` = '2018-02-01 03:44:14', `updated_at` = '2018-02-01 03:44:14' where `id` = '13'
- update `comments` set `deleted_at` = '2018-02-01 03:44:14', `updated_at` = '2018-02-01 03:44:14' where `id` = '8'
- update `posts` set `deleted_at` = '2018-02-01 03:44:14', `updated_at` = '2018-02-01 03:44:14' where `id` = '11'
- update `books` set `deleted_at` = '2018-02-01 03:44:14', `updated_at` = '2018-02-01 03:44:14' where `id` = '13'
- update `books` set `updated_at` = '2018-02-01 03:48:46', `deleted_at` = '' where `id` = '13'
- update `borrowings` set `deleted_at` = '', `updated_at` = '2018-02-01 03:48:46' where `book_id` = '13' and `deleted_at` = '2018-02-01 03:44:14'
- update `posts` set `deleted_at` = '', `updated_at` = '2018-02-01 03:48:46' where `book_id` = '13' and `deleted_at` = '2018-02-01 03:44:14'
- update `qrcodes` set `deleted_at` = '', `updated_at` = '2018-02-01 03:48:46' where `book_id` = '13' and `deleted_at` = '2018-02-01 03:44:14'
- update `comment` set `deleted_at` = '', `updated_at` = '2018-02-01 03:48:46' where `post_id` = '8' and `deleted_at` = '2018-02-01 03:44:14'

2018-02-01 07:51 UTC, at-phutran2 reviewed
LGTM

2018-02-02 02:06 UTC, at-duyho commented
explain sql query. please, thank!

2018-02-02 08:48 UTC, at-minhphan commented
Em đã `explain` rồi ạ.

2018-02-05 08:29 UTC, at-phutran2 commented on app/Model/Favorite.php
> +
bỏ 1 dòng

2018-02-05 08:29 UTC, at-phutran2 commented on app/Model/Rating.php
> +
bỏ 1 dòng trắng

2018-02-05 08:36 UTC, at-phutran2 reviewed
LGTM

2018-02-06 01:54 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +        $timeDelete = Book::withTrashed()->select('deleted_at')->find($id);
- what's $timeDelete?

2018-02-06 01:56 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +            Favorite::withTrashed()->where('deleted_at', $timeDelete->deleted_at)->where('favoritable_type', 'App\\Model\\Book')->where('favoritable_id', $id)->restore();
- you should do not hardcode: 'App\\Model\\Book'

2018-02-06 01:57 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +            foreach ($listPostID as $postID) {
- refactor this code

2018-02-06 01:58 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +                foreach ($listComment as $comment) {
- refactor this code

2018-02-06 01:58 UTC, ghost requested changes
check my comment

2018-02-06 06:35 UTC, at-minhphan commented on app/Http/Controllers/Api/BookController.php
> +        $timeDelete = Book::withTrashed()->select('deleted_at')->find($id);
$timeDelete lấy giá trị deleted_at của book.
Dùng để restore các relationship bị xóa kéo theo book, tránh restore các relationship bị xóa trước đó.

2018-02-06 07:33 UTC, at-phutran2 reviewed
lgtm

2018-02-06 08:21 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +        $timeDelete = Book::withTrashed()->select('deleted_at')->find($id);
- nhưng hiện tại em đang get về một object. thì tên timeDelete nó không rõ ràng.

2018-02-06 10:12 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +            foreach ($posts as $post) {
- you should get array posts id and use whereIn to restore. In this case, you should don't use foreach statement.

2018-02-06 10:12 UTC, ghost requested changes
- check my comment

2018-02-06 11:01 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +            $posts = Post::withTrashed()->where('book_id', $id)->where('deleted_at', $timeDelete)->pluck('id')->toArray();
- change $posts to $postsId

2018-02-06 15:22 UTC, at-duyho commented
- please, update sql queries and explain it. thank you!

2018-02-07 10:43 UTC, at-duyho commented
- cần tạo 100 record mỗi loại để test phần delete và restore.

2018-02-09 02:21 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +            return response()->json(['book'=> $book, 'time' => $timeDelete], 200);
you should use Response:HtttpOK

2018-02-09 02:23 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +        } catch (\PDOException $e) {
- you should add catch Exception, because sometime will has exception which is not a PDOException.

2018-02-09 02:24 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +        } catch (\PDOException $e) {
you should add catch Exception, because sometime will has exception which is not a PDOException.

2018-02-09 02:28 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +            return response()->json(['book'=> $book], 200);
you should use Response:HtttpOK

2018-02-09 02:29 UTC, at-duyho commented on routes/web.php
> +    Route::post('books/{id}/restore', 'BookController@restore')->middleware('admin');
you should use method PUT for restore.

2018-02-09 02:29 UTC, ghost requested changes
check my comment

2018-02-21 04:20 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +                $message = "This book is not found";
- Message nên được define trong file language.

2018-02-21 04:21 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +            $message = "Successfully";
Message nên được define trong file language.

2018-02-21 04:21 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +            $message = "SQL Error";
Message nên được define trong file language.

2018-02-21 04:21 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +            $message = "This book is not found";
Message nên được define trong file language.

2018-02-21 04:21 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +            $message = "Successfully";
Message nên được define trong file language.

2018-02-21 04:22 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +        if ($restored === 0) {
- check lại xem dùng `if ($restored)` có khác với  `if ($restored === 0)` không?

2018-02-21 04:23 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +            $message = "SQL Error";
Message nên được define trong file language.

2018-02-21 04:24 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +            if ($deleted === 0) {
- check xem dùng `if ($deleted)` có khác `if ($deleted === 0)` không?

2018-02-21 04:25 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +        } catch (\PDOException $e) {
- nên thêm một catch Exception để bắt tất cả các ngoại lệ ngoài PDOException.

2018-02-21 04:27 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +            $postsID = Post::where('book_id', $id)->pluck('id')->toArray();
- nên đưa câu lệnh select ra ngoài Transaction.

2018-02-21 04:29 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +        $timeDelete = Book::withTrashed()->where('id', $id)->pluck('deleted_at')->first();
- nên dùng $deletedTime

2018-02-21 04:29 UTC, at-duyho commented on app/Http/Controllers/Api/BookController.php
> +        $timeDelete = Carbon::now();
- nên dùng $deleteTime

2018-02-21 04:30 UTC, ghost requested changes
check my comment.

2018-02-21 10:47 UTC, at-minhphan commented on app/Http/Controllers/Api/BookController.php
> +        if ($restored === 0) {
Dạ khác anh.

2018-02-21 10:47 UTC, at-minhphan commented on app/Http/Controllers/Api/BookController.php
> +            if ($deleted === 0) {
Dạ khác anh.

2018-02-22 03:43 UTC, ghost approved these changes
LGTM

2018-02-22 03:43 UTC, merged