Unitest delete comment
AT-PHPIntership/book-library pull request #151
Opened 2018-02-01 04:58 UTC by at-luanle

## Description
Unit test delete Comment
## Reference Requirements
- Product Backlog ID: #PBI-11
- Task ID: #PBI 11.6

## Reference Isuees
#{issue_id}

## Migrations
YES | NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-02-02 01:06 UTC, ghost requested changes

2018-02-02 01:16 UTC, at-luanle commented on tests/Browser/Pages/Backend/Posts/DeleteCommentTest.php
> +                    ->assertSee('OK')
ở đây mình chỉ cần nhìn thấy là được, ko cần phải dùng assertSeeIn

2018-02-02 01:16 UTC, at-luanle commented on tests/Browser/Pages/Backend/Posts/DeleteCommentTest.php
> +                    ->assertSee('Close')
mỗi function mỗi chức năng độc lập nên khi test ko thể rút gọn được

2018-02-02 01:16 UTC, at-luanle commented on tests/Browser/Pages/Backend/Posts/DeleteCommentTest.php
> +            $this->assertTrue(2 == $count);
dòng 120 là trước khi bấm Close xem có bao nhiêu dữ liệu. sau khi bấm Close nếu giữ liệu giữ nguyên thì đúng

2018-02-02 01:16 UTC, at-luanle commented on tests/Browser/Pages/Backend/Posts/DeleteCommentTest.php
> +                    ->assertSee('Close')
mỗi function test độc lập, nên ko thể gọi là dư được

2018-02-02 01:16 UTC, at-luanle commented on tests/Browser/Pages/Backend/Posts/DeleteCommentTest.php
> +                    ->assertSee('OK')
ở đâu chỉ cần test see Ok là được rồi

2018-02-02 01:16 UTC, at-luanle commented on tests/Browser/Pages/Backend/Posts/DeleteCommentTest.php
> +                    ->assertSee('Close')
mỗi function là test độc lập một chức năng

2018-02-02 01:17 UTC, at-luanle commented on tests/Browser/Pages/Backend/Posts/DeleteCommentTest.php
> +            $this->assertTrue(2 == $count);
ở đây : dòng 120 là trước khi thay đổi xem có bao nhiêu giữ liệu, sau khi nhấm Close xem giữ liệu thay đổi ko

2018-02-02 01:17 UTC, at-luanle commented on tests/Browser/Pages/Backend/Posts/DeleteCommentTest.php
> +                    ->assertSee('Close')
mỗi function test độc lập nhau

2018-02-02 02:31 UTC, ghost approved these changes

2018-02-02 02:37 UTC, at-nghiavo commented
LGTM

2018-02-02 04:20 UTC, ghost reviewed
please check my comment

2018-02-02 04:20 UTC, at-nghiavo commented on tests/Browser/Pages/Backend/Posts/DeleteCommentTest.php
> +    private $user;
đặt tên clear tí anh, user để login thì có thể đặt là adminUser or adminUserToLogin

2018-02-02 04:54 UTC, at-nghiavo commented
LGTM

2018-02-05 03:25 UTC, at-xinhnguyen commented on tests/Browser/Pages/Backend/Posts/DeleteCommentTest.php
> +    /**
add black line sau private $user;

2018-02-05 04:21 UTC, ghost approved these changes
LGTM

2018-02-05 04:21 UTC, merged