Admin Send Mail Reminder daily at 11:00 a.m
AT-PHPIntership/book-library pull request #159
Opened 2018-02-06 07:22 UTC by at-annguyen

## Description
function auto send mail
## Reference Requirements
- Product Backlog ID:
- Task ID:

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-02-06 07:42 UTC, ghost reviewed
Check my comment

2018-02-06 07:42 UTC, at-anhngo commented on app/Console/Kernel.php
> +                 ->dailyAt('11:00');
chỗ này có cần set timezone không, nhỡ nó lấy mặc định thì sao

2018-02-07 02:29 UTC, at-anhngo commented on app/Console/Commands/SendEmails.php
> +        $borrowings = Borrowing::with('books', 'users')->where('to_date', '=', null)->get();
ở đây chỉ có mình trường hợp những người chưa được gửi mail thôi?, theo yêu cầu 
+ Khi chạy command này, hệ thống sẽ lấy ra tất cả những user đang mượn sách với thời gian quá 2 tuần và chưa nhận được email nhắc nhở hoặc đã nhận nhưng cách hiện tại nhiều hơn 3 ngày.

2018-02-07 02:31 UTC, at-anhngo commented on app/Jobs/SendMailsJob.php
> +        }
nếu nhỡ đang gửi mà bị gì không gởi tiếp được thì sao?, cần có thêm 1 chức năng thông báo cho admin nếu có vấn đề gì hoặc gửi thành công

2018-02-07 02:33 UTC, at-anhngo commented
Thiếu explain query nữa

2018-02-08 14:14 UTC, ghost reviewed
check my comment

2018-02-22 07:07 UTC, at-anhngo commented
LGTM

2018-02-22 07:23 UTC, ghost requested changes

2018-02-22 07:23 UTC, at-vietpham commented on app/Jobs/SendMailsJob.php
> +                if (canSendMail($borrowing->date_send_email)) {
Anh nghĩ không cần phải chạy fucntion `canSendMail()` kiểm tra `date_send_email` khi query là được rồi.

2018-02-22 07:23 UTC, at-vietpham commented on app/Jobs/SendMailsJob.php
> +                        if ($borrowing->save() == false && !empty(Mail::failures())) {
dòng trên đã chạy `$borrowing->save()` rồi sao ở đây lại chạy tiếp?

2018-02-22 07:23 UTC, at-vietpham commented on app/Jobs/SendMailsJob.php
> +                $e->getMessage();
Phải ghi log message lỗi này, chứ chạy `$e->getMessage()` đâu có tác dụng gì

2018-03-07 02:47 UTC, ghost approved these changes
LGTM

2018-03-07 03:01 UTC, at-vietpham commented on app/Console/Kernel.php
> +                 ->dailyAt('11:00')
Define `11:00` vào config.

2018-03-07 03:01 UTC, at-vietpham commented on app/Http/Controllers/Admin/SendMailController.php
> +                        ->withErrors(['message' => trans('portal.messages.not_an_email')])
Dòng dưới lùi 1 tab (4 space) so với dòng ở trên thôi. Sửa lại tương tự như chổ khác trong pull request này.

2018-03-07 03:01 UTC, at-vietpham commented on app/Jobs/SendMailsJob.php
> +        $borrowings = Borrowing::with('books', 'users')->where('to_date', '=', null)
Dùng `whereNull` là được rồi

2018-03-07 03:01 UTC, at-vietpham commented on app/Jobs/SendMailsJob.php
> +                    continue;
Nên lưu log lại ở những trường hợp ko gửi được email

2018-03-07 03:01 UTC, at-vietpham commented on app/Console/Kernel.php
> +                 ->timezone('Asia/Ho_Chi_Minh');
Timezone send mail cũng cần define trong config.

2018-03-07 06:49 UTC, at-vietpham commented on app/Jobs/SendMailsJob.php
> +                    \Log::info($validator->fails());
Log nên đủ thông tin. Nếu log này được khi thì chỉ có hiển thị message validation. Xem lại log không thể biết được log này dùng để làm gì. Nên khi rõ ra.
```php
\Log::info("Schedule sent mail to remined borrowing book");
foreach ($borrowings as $borrowing) {
    \Log::info("Start send main to: " + $email);
    if ($validator->fails()) {
        \Log::error($validator->fails());
    }
    // .....
    \Log::info("Send Success");
}
\Log::info("End schedule sent mail to remined borrowing book");
```

2018-03-07 08:11 UTC, at-vietpham commented
LGTM ☯️

2018-03-07 08:11 UTC, merged