Migration
AT-PHPIntership/book-library pull request #3
Opened 2017-12-30 10:33 UTC by at-annguyen

## Description
Create Data Table By Migration Laravel
## Reference Requirements
- Product Backlog ID: PBI-0
- Task ID: #0.3

## Migrations
YES 

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2017-12-31 14:52 UTC, at-anhngo commented on database/migrations/2017_12_30_034453_create_books_table.php
> +            $table->string('description');
books table does not have price column

2017-12-31 14:52 UTC, at-anhngo commented on database/migrations/2017_12_30_034453_create_books_table.php
> +            $table->integer('total_rating');
avg_rating and integer must have default value
--> default value = 0

2017-12-31 14:53 UTC, at-anhngo commented on database/migrations/2017_12_30_034453_create_books_table.php
> +            $table->tinyInteger('status');
status must have default value
--> default value = 1

2017-12-31 16:16 UTC, at-anhngo commented on database/migrations/2017_12_30_034453_create_books_table.php
> +            $table->float('avg_rating')->defautl(0.0);
incorrect function
-->defautl(0.0) => default(0.0)

2018-01-02 04:57 UTC, at-xinhnguyen commented on database/migrations/2017_12_30_034315_create_categories_table.php
> +        Schema::create('categories', function (Blueprint $table) {
please change the table name to the singular

2018-01-02 15:06 UTC, at-duyho commented on database/migrations/2014_10_12_000000_create_user_table.php
> +            $table->tinyInteger('role')->default(0);
- you should add comment for role.
ex: $table->tinyInteger('role')->default(0)->comment="0: admin; 1:user"

2018-01-02 15:06 UTC, at-duyho commented on database/migrations/2014_10_12_000000_create_user_table.php
> +        Schema::create('user', function (Blueprint $table) {
- table name have to a plural noun

2018-01-02 15:06 UTC, at-duyho commented on database/migrations/2017_12_30_034315_create_category_table.php
> +        Schema::create('category', function (Blueprint $table) {
- table name have to a plural noun

2018-01-02 15:07 UTC, at-duyho commented on database/migrations/2018_01_02_043417_create_donator_table.php
> +        Schema::create('donator', function (Blueprint $table) {
- table name have to a plural noun

2018-01-02 15:07 UTC, at-duyho commented on database/migrations/2018_01_02_065758_create_book_table.php
> +        Schema::create('book', function (Blueprint $table) {
- table name have to a plural noun

2018-01-02 15:08 UTC, at-duyho commented on database/migrations/2018_01_02_065758_create_book_table.php
> +            $table->tinyInteger('status')->default(1);
- you should add comment for column

2018-01-02 15:08 UTC, at-duyho commented on database/migrations/2018_01_02_065832_create_borrow_table.php
> +        Schema::create('borrow', function (Blueprint $table) {
- table name have to a plural noun

2018-01-02 15:08 UTC, at-duyho commented on database/migrations/2018_01_02_065902_create_post_table.php
> +        Schema::create('post', function (Blueprint $table) {
- table name have to a plural noun

2018-01-02 15:08 UTC, at-duyho commented on database/migrations/2018_01_02_065902_create_post_table.php
> +            $table->tinyInteger('type');
- add comment for column

2018-01-02 15:09 UTC, at-duyho commented on database/migrations/2018_01_02_065930_create_comment_table.php
> +        Schema::create('comment', function (Blueprint $table) {
- table name have to a plural noun

2018-01-02 15:09 UTC, at-duyho commented on database/migrations/2018_01_02_070003_create_like_table.php
> +        Schema::create('like', function (Blueprint $table) {
- table name have to a plural noun

2018-01-02 15:11 UTC, at-duyho commented on database/migrations/2018_01_02_081818_create_rating_table.php
> +        Schema::create('rating', function (Blueprint $table) {
- table name have to be a plural noun

2018-01-02 15:11 UTC, ghost requested changes
check my comment.

2018-01-03 10:32 UTC, at-anhngo commented on database/migrations/2018_01_02_065758_create_book_table.php
> +            $table->float('avg_rating')->defautl(0.0);
default, not defautl

2018-01-03 16:05 UTC, at-xinhnguyen commented on database/migrations/2017_12_30_034315_create_categories_table.php
> +            $table->softDeletes();
a nghĩ Category k cần softDeletes đâu

2018-01-04 09:10 UTC, ghost approved these changes
LGTM

2018-01-04 09:19 UTC, merged