Model and Relationship
AT-PHPIntership/book-library pull request #4
Opened 2017-12-30 14:51 UTC by at-annguyen

## Description
A few sentences describing the overall goals of the pull request's commits.
## Reference Requirements
- Product Backlog ID: PBI-0
- Task ID: #0.3

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2017-12-31 15:05 UTC, at-anhngo commented on app/Model/Book.php
> +        'donate_by',
missing field price

2018-01-02 10:14 UTC, at-annguyen commented
![library_books](https://user-images.githubusercontent.com/26828657/34480677-5abdd864-efe0-11e7-98a3-cb2bb55ac474.png)

2018-01-02 14:46 UTC, at-duyho commented on app/Model/Comment.php
> +    protected $table = 'comment';
- table name have to a plural noun

2018-01-02 14:46 UTC, at-duyho commented on app/Model/Book.php
> +    protected $table = 'book';
- table name have to a plural noun

2018-01-02 14:46 UTC, at-duyho commented on app/Model/Borrow.php
> +    protected $table = 'borrow';
- table name have to a plural noun

2018-01-02 14:53 UTC, at-duyho commented on app/Model/Category.php
> +    protected $table = 'category';
- table name have to a plural noun

2018-01-02 14:54 UTC, at-duyho commented on app/Model/Donator.php
> +    protected $table = 'donator';
- table name have to a plural noun

2018-01-02 14:54 UTC, at-duyho commented on app/Model/Like.php
> +    protected $table = 'like_and_share';
- table name have to a plural noun

2018-01-02 14:55 UTC, at-duyho commented on app/Model/Post.php
> +    protected $table = 'post';
- table name have to a plural noun

2018-01-02 14:55 UTC, at-duyho commented on app/Model/Rating.php
> +    protected $table = 'rating';
- table name have to a plural noun

2018-01-02 14:56 UTC, ghost requested changes
please check my comment. thank you

2018-01-04 09:17 UTC, ghost approved these changes
LGTM

2018-01-04 09:19 UTC, merged