Get data search for book page by author name all
AT-PHPIntership/book-library pull request #49
Opened 2018-01-06 09:46 UTC by at-luanle

## Description
Create function search for book page by author, name, all
## Reference Requirements
- Product Backlog ID: #PBI-6
As a manager, in page list books, I can search/filter books by Author, Name
- Task ID: #PBI-6.1
Get data

## Migrations
![screenshot from 2018-01-06 16 46 17](https://user-images.githubusercontent.com/33856992/34638585-29067adc-f301-11e7-9c9a-ed9e06e4e3fb.png)
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-01-10 08:36 UTC, at-nghiavo commented
conflicts rồi a Luân

2018-01-11 07:09 UTC, at-xinhnguyen commented on resources/assets/js/book.js
> +    alert('hello');
file này nếu k dùng thì đừng add vào Luân ơi

2018-01-11 07:32 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/BookController.php
> +                    ->paginate(config('define.page_length'));
làm thế này bị lặp code rồi.  chỉ cần check input_search tồn tại thì add thêm 1 where cho attribute đó thôi

2018-01-11 07:39 UTC, at-xinhnguyen commented on resources/views/backend/books/list.blade.php
> +                                    <p class="text-info h1">Sorry, the page you are looking for could not be found.</p>
trans những text này đi Luân 
Sorry, the page you are looking for could not be found

2018-01-11 07:50 UTC, at-xinhnguyen commented on resources/views/backend/books/list.blade.php
> +                        <form action="{{ url('admin/books') }}" method="GET" id="frm-search">
dùng route thay url luôn cho đồng bộ Luân.

2018-01-11 09:42 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/BookController.php
> +        } else {
Tại sao phải làm cả đống if else thế này Luân, chỉ cần check. nếu có $request->has('name') thì where name. 
nếu có author thì where author. là được rồi.

2018-01-11 10:19 UTC, ghost requested changes
pls check my cmt

2018-01-11 10:19 UTC, at-vienle commented on app/Http/Controllers/Admin/BookController.php
> +        if ($request->has('name')  || $request->has('author')) {
chỗ này sao phức tạp vậy, dùng 1 cái scope query ở model là được rồi, check trong request có cái param nào thì add where cho column tương ứng

2018-01-12 01:17 UTC, at-xinhnguyen commented on resources/views/backend/books/list.blade.php
> +                                  <a href="{{ url('admin/books')}}" class="btn btn-default text-info">ComeBack</a>
trans ComeBack đi Luân

2018-01-12 01:25 UTC, at-xinhnguyen commented on resources/lang/en/book.php
> +    'message' => 'Sorry, Not Be Found.'
`message` đâu liên quan chi tới `Sorry, Not Be Found.`
đổi tên hoặc chuyển sang file tên `common` đi Luân
'message' => [
'not_found' => 'Sorry, Not Be Found'
]

2018-01-12 02:55 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/BookController.php
> +        $books = $books->with('borrowings')->withCount('borrowings')
cái này không dùng thì remove đi Luân: with('borrowings')

2018-01-12 02:59 UTC, at-xinhnguyen commented on app/Model/Book.php
> +     * @param Model  $query query of Model
param này phải là \Illuminate\Database\Eloquent\Builder $query

2018-01-12 02:59 UTC, at-xinhnguyen commented on app/Model/Book.php
> +     * @return mixed
chỗ này phải return \Illuminate\Database\Eloquent\Builder

2018-01-12 03:01 UTC, at-xinhnguyen commented on resources/views/backend/books/list.blade.php
> +                                    <input type="text" class="form-control" id="search-name" name="name" placeholder="Enter Name..." value="{{ Request::get('name')}}">
trans cho Enter Name nhé

2018-01-12 03:01 UTC, at-xinhnguyen commented on resources/views/backend/books/list.blade.php
> +                                    <input type="text" class="form-control" id="search-author" name="author" placeholder="Enter Author..." value="{{ Request::get('author')}}">
trans cho enter author nhé

2018-01-12 03:05 UTC, at-xinhnguyen commented on resources/lang/en/book.php
> +    'common' => 'Sorry, Not Be Found.'
hiểu nhầm ý mình rồi. 
Luân thấy common với Sorry, Not Be Found. có liên quan với nhau không? không đúng không?
đổi lại đi. message => ['not_found' => 'Sorry, Not be found']  chẳng hạn

2018-01-12 03:31 UTC, at-xinhnguyen commented
reset file ccomposer.lock  đi Luân

2018-01-12 03:33 UTC, merged