Admin Homepage UI
AT-PHPIntership/book-library pull request #55
Opened 2018-01-08 14:54 UTC by at-annguyen

## Description
Create HomePage UI
## Reference Requirements
- Product Backlog ID: PBI-1
- Task ID: TI-1

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-01-09 22:28 UTC, at-anhngo commented
fix conflict

2018-01-10 11:23 UTC, at-duyho commented
-please! across review before assign to me.

2018-01-11 03:05 UTC, ghost requested changes
check my comment

2018-01-11 03:05 UTC, at-anhngo commented on resources/views/backend/homepage/index.blade.php
> +
loại xuống không cần thiết

2018-01-11 03:05 UTC, at-anhngo commented on resources/views/backend/homepage/index.blade.php
> +
xuống dòng không cần thiết

2018-01-11 03:05 UTC, at-anhngo commented on resources/views/backend/homepage/index.blade.php
> +
xuống dòng không cần thiết

2018-01-11 03:05 UTC, at-anhngo commented on routes/web.php
> +		Route::resource('books', 'BookController');
tấp vào lề

2018-01-11 07:22 UTC, ghost approved these changes

2018-01-11 07:23 UTC, at-anhngo commented
LGTM

2018-01-11 07:37 UTC, ghost approved these changes
LGTM

2018-01-11 07:38 UTC, merged