Seeder after fix DB
AT-PHPIntership/book-library pull request #66
Opened 2018-01-10 11:11 UTC by at-annguyen

## Description
Add and change dataseeder for all of table
## Reference Requirements
- Product Backlog ID: PBI-0
- Task ID: #0.3

## Migrations
YES 

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-01-11 02:52 UTC, ghost submitted a review, later dismissed
Check my comment

2018-01-11 02:52 UTC, at-anhngo commented on database/factories/ModelFactory.php
>          'QRcode' => $faker->ean13,
chỗ này có thể chỉnh lại thành BAT-xxxxx cho đúng định dạng không?

2018-01-12 08:46 UTC, at-xinhnguyen commented on database/factories/ModelFactory.php
> +        'role'                     => rand(0, 1),
format lại cho dễ nhìn tí An ơi, 
các dấu => thẳng hàng với nhau ấy

2018-01-12 09:21 UTC, at-annguyen commented on database/factories/ModelFactory.php
> +        'role'                     => rand(0, 1),
ok rồi anh :+1:

2018-01-15 03:27 UTC, at-duyho commented
- pleas, cross review before assign to me. thank you!

2018-01-15 07:37 UTC, at-duyho commented
-But, I didn't found his approvement.

2018-01-15 09:48 UTC, at-anhngo commented
LGTM

2018-01-15 10:40 UTC, at-duyho commented on database/factories/ModelFactory.php
> +        'to_date'   => $faker->datetime,
to_date should after from_date. You shoud use: to_date = from_date + constant.

2018-01-15 10:43 UTC, at-duyho commented on database/factories/ModelFactory.php
> +        'favoritable_type' => $faker->randomElement(['books', 'comments', 'posts'])
- please check values of favoritable_type? normally, values is a namespace of class.

2018-01-15 10:45 UTC, ghost requested changes
Please, check my comment

2018-01-16 03:57 UTC, ghost approved these changes
LGTM

2018-01-16 03:58 UTC, merged