Admin homepage get data
AT-PHPIntership/book-library pull request #76
Opened 2018-01-12 10:08 UTC by at-annguyen

## Description
Get Count User, Book, Category
## Reference Requirements
- Product Backlog ID: PBI-1
- Task ID: TI-1

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:
-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)
- select count(*) as aggregate from `users` where `users`.`deleted_at` is null;
- select count(*) as aggregate from `books`;
- select count(*) as aggregate from `categories`;

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)
![category](https://user-images.githubusercontent.com/26828657/34869951-33d06ea0-f7bb-11e7-9ad1-12efbbeb297c.png)
![book](https://user-images.githubusercontent.com/26828657/34869952-33fbb164-f7bb-11e7-86ea-bab41faa532b.png)
![user](https://user-images.githubusercontent.com/26828657/34869953-34256306-f7bb-11e7-86c1-793ea6907087.png)

2018-01-13 05:13 UTC, at-anhngo commented
LGTM

2018-01-13 05:14 UTC, ghost approved these changes

2018-01-15 03:32 UTC, at-duyho commented on app/Helpers/common.php
> +        $count = '';
- you should define clearly type for count variable.

2018-01-15 03:34 UTC, at-duyho commented on app/Helpers/common.php
> +                break;
- when you use block default, you should not need break statement.

2018-01-15 03:35 UTC, at-duyho commented on app/Helpers/common.php
> +            case 'users':
- you should define constant. I think you should use: nameClass::class.

2018-01-15 03:37 UTC, at-duyho commented on app/Helpers/common.php
> +    function getCount($name)
- what's purpose?

2018-01-15 03:38 UTC, ghost requested changes
check my comment. thank!

2018-01-15 15:31 UTC, ghost approved these changes
LGTM

2018-01-15 15:31 UTC, merged