Filter top 5 donator top 10 borrowed
AT-PHPIntership/book-library pull request #78
Opened 2018-01-16 02:06 UTC by at-annguyen

## Description
A few sentences describing the overall goals of the pull request's commits.
## Reference Requirements
- Product Backlog ID: PBI-1
- Task ID: #1.1

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)
select `id`, `name`, `author`, `avg_rating`, `total_rating`, 
	(select count(*) from `borrowings` 
		where `books`.`id` = `borrowings`.`book_id` and `borrowings`.`deleted_at` is null) 
	as `borrowings_count` 
from `books` order by `borrowings_count` desc limit 10
select count(*) as aggregate from `users` where `users`.`deleted_at` is null
select count(*) as aggregate from `books`
select count(*) as aggregate from `categories`
select count(*) as aggregate from `posts` where `posts`.`deleted_at` is null

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)
![screenshot from 2018-01-16 09-04-38](https://user-images.githubusercontent.com/26828657/34968588-9406cf1a-fa9c-11e7-9801-8ad9e71348f1.png)

2018-01-17 06:01 UTC, ghost requested changes

2018-01-17 06:01 UTC, at-anhngo commented on resources/views/backend/books/list.blade.php
> +      </div>
đóng thẻ div bị dư space

2018-01-17 06:01 UTC, at-anhngo commented on resources/views/backend/users/index.blade.php
> +          <div class="box-body" id="abc">
id="abc" là gì

2018-01-17 06:04 UTC, at-anhngo commented
sửa lại mô tả cho pr

2018-01-23 03:26 UTC, at-anhngo commented
fix conflict

2018-01-23 05:11 UTC, ghost requested changes
Check my comment

2018-01-23 05:11 UTC, at-anhngo commented on app/Http/Controllers/Admin/UserController.php
> +        $limit = $request->input('limit');
nếu đã kiểm tra limit trong này chỉ bằng 5 thì không cần phải lấy từ url làm gì, cứ để 1 const là được

2018-01-23 05:11 UTC, at-anhngo commented on app/Http/Controllers/Admin/BookController.php
> +        if ($filter == 'borrowed' && $limit == 10) {
chỉ cần đặt const là được, nếu đã truyền tham số vào url rồi get thì cần gì phải if else

2018-01-23 07:08 UTC, at-anhngo commented
LGTM

2018-01-23 07:08 UTC, ghost approved these changes

2018-01-23 15:20 UTC, at-duyho commented
- fix hoặc trả lời hết các comment.

2018-01-24 03:21 UTC, at-annguyen commented on app/Http/Controllers/Admin/UserController.php
> +        $limit = $request->input('limit');
sử dụng limit cho nhiều trường hợp filter

2018-01-24 07:28 UTC, at-duyho commented on app/Http/Controllers/Admin/BookController.php
> +        if ($filter == Book::BORROWED && $limit == config('define.page_length')) {
- you don't need check $limit because if limit is null laravel set default 15

2018-01-24 07:30 UTC, at-duyho commented on app/Http/Controllers/Admin/BookController.php
> +            $books = $books->withCount('borrowings')->sortable()->orderby('id', 'desc')->paginate(config('define.page_length'));
- refactor this code. in some case will duplicate query.

2018-01-24 07:32 UTC, at-duyho commented on app/Http/Controllers/Admin/UserController.php
> +        if ($filter == User::DONATOR && $limit == config('define.page_length')/2) {
- you don't need check $limit

2018-01-24 07:33 UTC, ghost requested changes
check my comment and generate all query in request.

2018-02-06 02:23 UTC, at-duyho commented on resources/views/backend/books/list.blade.php
> +                    @if($books instanceof \Illuminate\Pagination\AbstractPaginator)
- what's is this? I don't understand.

2018-02-06 02:23 UTC, at-duyho commented on resources/views/backend/users/index.blade.php
> +                  @if($users instanceof \Illuminate\Pagination\AbstractPaginator)
- what is this? I don't understand.

2018-02-06 03:44 UTC, at-duyho commented on app/Http/Controllers/Admin/BookController.php
>          if ($request->has('uid') && $request->has('filter')) {
You should discuss and refactor code.

2018-02-06 03:44 UTC, ghost requested changes
please check my comment.

2018-03-05 04:24 UTC, at-annguyen commented on resources/views/backend/books/list.blade.php
> +                    @if($books instanceof \Illuminate\Pagination\AbstractPaginator)
it's check use paginate or not

2018-03-05 04:24 UTC, at-annguyen commented on resources/views/backend/users/index.blade.php
> +                  @if($users instanceof \Illuminate\Pagination\AbstractPaginator)
it's check use paginate or not

2018-03-06 01:38 UTC, ghost approved these changes
LGTM

2018-03-06 01:39 UTC, merged