Change file layouts folder
AT-PHPIntership/book-library pull request #88
Opened 2018-01-17 07:53 UTC by at-annguyen

## Description
Change left-bar and header get information of user login
## Reference Requirements
- Product Backlog ID: PBI-1
- Task ID: TI-1

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-01-17 08:08 UTC, at-anhngo commented on resources/views/backend/layouts/partials/left-bar.blade.php
>                <small class="label pull-right bg-purple">{{ getCount(App\Model\Post::class) }}</small>
4 spaces

2018-01-18 02:10 UTC, ghost requested changes
Check my comment

2018-01-18 02:10 UTC, at-anhngo commented on resources/views/backend/layouts/partials/header.blade.php
> +                <small>{{__('dashboard.member')}} : {{ date('d-m-Y', strtotime(Auth::user()->created_at)) }}</small>
nên sử dụng Carbon để format date

2018-01-19 07:32 UTC, ghost requested changes
check my comment

2018-01-19 07:32 UTC, at-anhngo commented on resources/views/backend/layouts/partials/header.blade.php
> +                <a href="{{route('users.show', Auth::user()->employee_code)}}" class="btn btn-default btn-flat">{{__('Profile')}}</a>
nên bỏ vào 1 file lang

2018-01-19 07:50 UTC, at-anhngo commented
fix circle ci

2018-01-19 09:51 UTC, at-anhngo commented
LGTM

2018-01-19 09:51 UTC, ghost approved these changes

2018-01-22 02:59 UTC, at-duyho commented on app/Helpers/common.php
> +    function areActiveRoute(array $routes, $output = "active")
- tại sao lại dùng cả hai hàm cho một chức năng?

2018-01-22 03:00 UTC, ghost requested changes
check my comment

2018-01-23 01:47 UTC, ghost requested changes
check my comment

2018-01-23 15:29 UTC, at-duyho commented
fix CI

2018-01-24 07:37 UTC, ghost approved these changes
LGTM

2018-01-24 07:38 UTC, merged